services:

  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'TeST@+$-'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer'
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    networks:
      - mssql_network
    volumes:
      - mssql_volume:/var/opt/mssql
      - /data:/data
      # - ./log:/var/opt/mssql/log
      # - ./secrets:/var/opt/mssql/secrets

volumes:
  mssql_volume:
    name: mssql_volume

networks:
  mssql_network:
    driver: bridge
    name: mssql_network

